// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe41hldSz4D56i4g7TRs4IyXaigNoAikM',
    appId: '1:394008708625:web:b91a535a6c153559ae53b0',
    messagingSenderId: '394008708625',
    projectId: 'purity-c0f9a',
    authDomain: 'purity-c0f9a.firebaseapp.com',
    databaseURL: 'https://purity-c0f9a-default-rtdb.firebaseio.com',
    storageBucket: 'purity-c0f9a.appspot.com',
    measurementId: 'G-0138BGRGC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSvyxG2G8D0M-Q29lc7lsV83uKRkuBMeE',
    appId: '1:394008708625:android:b4d949acf97e5d47ae53b0',
    messagingSenderId: '394008708625',
    projectId: 'purity-c0f9a',
    databaseURL: 'https://purity-c0f9a-default-rtdb.firebaseio.com',
    storageBucket: 'purity-c0f9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCyifCUZsba_QIalNIZz45h1sZSBC2Vhk',
    appId: '1:394008708625:ios:d9e7c02cb21169e0ae53b0',
    messagingSenderId: '394008708625',
    projectId: 'purity-c0f9a',
    databaseURL: 'https://purity-c0f9a-default-rtdb.firebaseio.com',
    storageBucket: 'purity-c0f9a.appspot.com',
    iosClientId: '394008708625-6qft6vkrdbo233lsgp00m4s1934nlvhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.purityapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCyifCUZsba_QIalNIZz45h1sZSBC2Vhk',
    appId: '1:394008708625:ios:d9e7c02cb21169e0ae53b0',
    messagingSenderId: '394008708625',
    projectId: 'purity-c0f9a',
    databaseURL: 'https://purity-c0f9a-default-rtdb.firebaseio.com',
    storageBucket: 'purity-c0f9a.appspot.com',
    iosClientId: '394008708625-6qft6vkrdbo233lsgp00m4s1934nlvhv.apps.googleusercontent.com',
    iosBundleId: 'com.example.purityapp',
  );
}
